<Project>
  <ItemGroup>
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.10" />
    <PackageVersion Include="ZstdSharp.Port" Version="0.8.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageVersion Include="H.NotifyIcon.Wpf" Version="2.1.4" />
    <PackageVersion Include="WPF-UI" Version="3.0.5" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
