<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>tt-win</AssemblyName>
    <RootNamespace>TokenTracker.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TokenTracker.Core\TokenTracker.Core.csproj" />
  </ItemGroup>

</Project>
